### ISSUE TITLE
Problem with image on Rsapberry 3 B+

### ISSUE THREAD

**Issue by trybikowski** [htruong/crankshaft#700]
Hi,

I’m encountering a problem while trying to install the image on my Raspberry Pi 3 B+. Below are the details of the issue:

1. During the installation, I encountered this error:
![PXL_20250106_143447013](https://github.com/user-attachments/assets/b08d6cf4-5f0e-4d93-9690-36f978fa6149)

2. After booting, the system displays the following screen:
![PXL_20250106_143850388](https://github.com/user-attachments/assets/647bf538-bb63-42bf-8260-9f8b9fd1ff0e)

I am using the following setup:

Device: Raspberry Pi 3 B+
Image: 20250105-Debian_buster-armhf.zip (installed on an SD card)

**Comment by SonOfGib** [comment]
I am seeing the same thing, I'll look into it.

**Comment by matt2005** [comment]
I've switched to a different process to update the compiled binaries to speed up the build time, but i missed a step in the process.
I've added the ldconfig step and now it is working. I'm building a new release so it should be ready in the next 30mins

**Comment by SonOfGib** [comment]
I will check once its built, but I think the issue is that the autoapp binary in prebuilts is expecting `libaasdk.so.3` but that symlink is not present in /usr/local/lib. I checked the version I built a few months ago and that link _is_ present. I must have modified the crankshaft pigen script and forgot.

At least, running ldconfig doesn't seem to solve it on the test image I burned.

**Comment by matt2005** [comment]
It's not fixed but it's not the ldconfig issue

**Comment by SonOfGib** [comment]
I actually just burned 20250107 to an sd card and its working, despite what I thought above. Are you seeing issues?

**Comment by matt2005** [comment]
I tested on a pi2, but that might be a separate issue. I'll dig out the pi3 and try that one.

**Comment by matt2005** [comment]
@trybikowski this should be resolved in the latest pre-release

**Comment by trybikowski** [comment]
Hi @matt2005,

I’ve already installed the latest image (from January 11). The fault after installation still exists, but the image works. Android Auto starts properly.

In my opinion, the issue with the light sensor (TL2561) still persists. It seems to "read" the lux value at startup, but the state doesn’t change afterward.

I’ve also assembled the RTC DS3231 time chip (insted TL2561). While the time is remembered, Crankshaft doesn’t adjust between day and night based on the settings (day: 8:00, night: 17:00). I have to manually switch between day and night using the button in the main menu. Is this ok?

**Comment by matt2005** [comment]
Please raise a separate issue for the light sensor issue. Please remember to include hardware details and the debug logs.

**Comment by aegidius77** [comment]
Hi,

No error when flashing the SD card, but same error as @trybikowski when installing 20250111 or 20250108 (both arm7-pi2 or armhf). I used to install them without any errors until today.

pi 3B v1.2
official 7 inches screen

<img width="792" height="502" alt="Image" src="https://github.com/user-attachments/assets/ecfdfbdd-17e4-4406-b004-2399a74be41c" />

![Image](https://github.com/user-attachments/assets/caac8f7d-dc1c-4893-94d3-7a3a14d02314)


> Hi,
> 
> I’m encountering a problem while trying to install the image on my Raspberry Pi 3 B+. Below are the details of the issue:
> 
>     1. During the installation, I encountered this error:
>        ![PXL_20250106_143447013](https://github.com/user-attachments/assets/b08d6cf4-5f0e-4d93-9690-36f978fa6149)
> 
>     2. After booting, the system displays the following screen:
>        ![PXL_20250106_143850388](https://github.com/user-attachments/assets/647bf538-bb63-42bf-8260-9f8b9fd1ff0e)
> 
> 
> I am using the following setup:
> 
> Device: Raspberry Pi 3 B+ Image: 20250105-Debian_buster-armhf.zip (installed on an SD card)

**Comment by lazyjavvy** [comment]
@aegidius77 Can you try 20250111-Debian_buster-armhf.zip? I tried this image on a pi4b and it works.

**Comment by aaronjamt** [comment]
> [@aegidius77](https://github.com/aegidius77) Can you try 20250111-Debian_buster-armhf.zip? I tried this image on a pi4b and it works.

I tried that version on my own RPi3B+ and encountered the same issue.
